# Generated by Django 5.0.6 on 2024-06-26 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "address_code",
                    models.CharField(
                        default=0, max_length=255, primary_key=True, serialize=False
                    ),
                ),
                ("address_city", models.CharField(default="", max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("company_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Orders",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("profile_name", models.CharField(max_length=255)),
                ("profile_lastname", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Clients",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("client_name", models.CharField(default="", max_length=255)),
                ("client_firstname", models.CharField(default="", max_length=255)),
                ("client_lastname", models.CharField(default="", max_length=255)),
                ("client_username", models.CharField(default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client_address",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Clients.address",
                    ),
                ),
                (
                    "client_company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Clients.company",
                    ),
                ),
                (
                    "client_orders",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Clients.orders",
                    ),
                ),
                (
                    "client_profile",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Clients.profile",
                    ),
                ),
            ],
        ),
    ]
