# Generated by Django 5.0.6 on 2024-06-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='Adresse',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
