# Generated by Django 5.0.6 on 2024-06-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0004_address_company_orders_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='City',
        ),
        migrations.RemoveField(
            model_name='address',
            name='postalCode',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='Order',
        ),
        migrations.AddField(
            model_name='address',
            name='address_city',
            field=models.CharField(default='', max_length=255),
        ),
    ]
