# Generated by Django 5.0.6 on 2024-06-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0006_remove_address_id_address_address_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_code',
        ),
        migrations.AddField(
            model_name='address',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
