# Generated by Django 5.0.6 on 2024-06-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0007_remove_address_address_code_address_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='Nom',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
