# Generated by Django 5.0.6 on 2024-06-26 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0008_clients_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='Order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Clients.orders'),
        ),
    ]
