# Generated by Django 5.0.6 on 2024-06-26 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0009_clients_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='Order',
        ),
    ]
