# Generated by Django 5.0.6 on 2024-06-26 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0010_remove_clients_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Prenom',
            new_name='profile_lastname',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Nom',
            new_name='profile_name',
        ),
    ]
